Auto merge of #6015 - olleolleolle:fix/6013-rb_user_install_into_preserve_keys, r=segiddins
Add RB_USER_INSTALL to preserved ENV keys

This PR adds the environment variable `RB_USER_INSTALL` to the list of preserved keys. That variable is used on FreeBSD.

  - see #6013

Without this change, Bundler's usage of it with the shared helpers to set a preserved env would raise this:

> ArgumentError: new key RB_USER_INSTALL

(This seems to be the only env var which is used but not listed in the preserved keys list.)

(cherry picked from commit b3cbf4a7538ca1d506a81706171b81c173bd048c)