Auto merge of #5389 - Shekharrajak:5384_inject_usage, r=segiddins
Show inject usage when args are passed incorrectly

Closes #5384

Now it shows the error :

```
$ bundle inject "gem_name" 1 "v"
ERROR: "bundle inject" was called with arguments ["gem_name", "1", "v"]
Usage: "bundle inject GEM VERSION"
$ bundle inject "gem_name" "v" 1
ERROR: "bundle inject" was called with arguments ["gem_name", "v", "1"]
Usage: "bundle inject GEM VERSION"

```

(cherry picked from commit ec5cab34d3b12467433ca1a1eafc460e42834084)