Remove -I option from alias.
- This causes the following exception:

RuntimeError: LazySpecification has not been materialized yet (calling :required_ruby_version [])

- This error was introduced in 1.10.6 when the bundle script was moved from
  bin/ to exe/.
- Removing the option allows the alias to work as expected.